### ISSUE TITLE
Bibblio Authorization Python

### ISSUE THREAD

**Issue by renevatium** [proversity-org/bibblio-api-python#3]
Bibblio auth for Python api wrapper (via ruby auth service)

**Comment by renevatium** [comment]
Please check with Dominic re olya/auth service when you'reback online

**Comment by jagonzalr** [comment]
@renevatium this is just a wrapper, so that is why I also added the auth. For any person that want to use this. In reality the wrapper is used inside another project (like edX) along Dom's ruby auth service without using the auth of the Python wrapper.

**Comment by renevatium** [comment]
awesome =] wasn't 100% sure, understood.
